main: main.c Init.c RecordStream.c NetworkChecker.c battery_driver/bq27xxx_battery.c battery_driver/bq27xxx_battery_i2c.c
	gcc -o main main.c Init.c RecordStream.c NetworkChecker.c battery_driver/bq27xxx_battery.c battery_driver/bq27xxx_battery_i2c.c -lwiringPi -I.
